version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=expected
      - POSTGRES_PASSWORD=expected
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  data: {}
