version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=expected
      - POSTGRES_PASSWORD=expected
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=expected
      - RABBITMQ_DEFAULT_PASS=expected
      - RABBITMQ_DEFAULT_VHOST=expected
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  postgres: {}
  rabbitmq: {}
