version: '3.4'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=expected
      - POSTGRES_PASSWORD=expected
      - TZ=Europe/Amsterdam
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_AUTH: "token"
      REGISTRY_AUTH_TOKEN_REALM: "http://localhost:3001/registry/auth"
      REGISTRY_AUTH_TOKEN_SERVICE: "registry"
      REGISTRY_AUTH_TOKEN_ISSUER: "auth_registry"
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: "/certs/server.crt"
      REGISTRY_AUTH_TOKEN_AUTOREDIRECT: "false"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: "- name: expected-hook\n  url: http://localhost:3001/registry/hook\n  timeout: 5s\n  threshold: 8\n  backoff: 10s"
    volumes:
      - ./certs:/certs
volumes:
  data: {}
