version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=expected
      - POSTGRES_PASSWORD=expected
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  registry:
    restart: always
    image: registry:latest
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=http://localhost:3000/registry/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=registry
      - REGISTRY_AUTH_TOKEN_ISSUER=auth_registry
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/server.crt
      - REGISTRY_AUTH_TOKEN_AUTOREDIRECT=false
      - REGISTRY_NOTIFICATIONS_ENDPOINTS_NAME=hook
      - REGISTRY_NOTIFICATIONS_ENDPOINTS_URL=http://localhost:3000/registry/hook
      - REGISTRY_NOTIFICATIONS_ENDPOINTS_TIMEOUT=1s
      - REGISTRY_NOTIFICATIONS_ENDPOINTS_THRESHOLD=5
      - REGISTRY_NOTIFICATIONS_ENDPOINTS_BACKOFF=1s
    volumes:
      - ./certs:/certs
volumes:
  data: {}
