### Create new container
POST http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: 7d93f590197e45d49101c25df6366618

{
  "name": "hell",
  "image": "google/golang-hello",
  "plan_id": "df6207bb-f897-402b-ac8a-9f310f92aa6c",
  "tags": ["123", "test"],
  "environment": {
    "PORT": "80"
  }
}

### Get list of all tags for owner id
GET http://localhost:3000/v1/containers
Authorization: ce41f7ca970745409a47079c2ebd62f2

### List containers
GET http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

### List images
GET http://localhost:3000/v1/images
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

### Detail image
GET http://localhost:3000/v1/images/redis:latest
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

### Delete image
DELETE http://localhost:3000/v1/images/redis:latest/sha256:478392fbb4f132b36b8ead3435087553ee7e6f0395b3d64987ae195268d13493
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

###