### Create new container
POST http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: ce41f7ca970745409a47079c2ebd62f2

{
  "name": "hello",
  "image": "google/golang-hello",
  "memory": 64,
  "tags": ["expectedsh", "test"],
  "environment": {
    "PORT": "80"
  }
}

### List containers
GET http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: c2e827438b6a4a26b8262d89e2673ed0




#### REGISTRY ENDPOINTS

### DELETE AN IMAGE
DELETE http://localhost:5000/v2/b431e1c9-3b04-42bd-83f5-47c05e49c70c/registry/manifests/sha256:b1165286043f2745f45ea637873d61939bff6d9a59f76539d6228abf79f87774
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZMWEE6WDQ0VDpPQjNaOjY2SUc6NEoyNjpZSFNZOllTSFg6V1c2UzpENTRGOk0yRUw6SkZMTTpGQlRXIn0.eyJpc3MiOiJhdXRoX3JlZ2lzdHJ5Iiwic3ViIjoiQWxleGlzLnZpc2NvZ2xpb3NpQG91dGxvb2suZnIiLCJhdWQiOiJyZWdpc3RyeSIsImV4cCI6MzYwMTU0OTgwMzkzOSwibmJmIjoxNTQ5ODAzOTI5LCJpYXQiOjE1NDk4MDM5MzksImp0aSI6IjU1NzcwMDY3OTE5NDc3Nzk0MTAiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6ImNlNWE4MGQ4LTNkYTItNDBjZi1iZDgxLTUwZGIwYzhiYTE2Mi9oZWxsby13b3JsZCIsImFjdGlvbnMiOlsiZGVsZXRlIl19XX0.oH-WL7EyC4KZPlty6C9aSlLSTBZsoVfGVvTe31AaUgLnJqXwsGifvtF5NCXiVkveD5jcT7rlalI8CjqM-Sq824dielYN98RXWpkpw1hOhgpAJvWMt3jTjdGbyLw0QDpqd7nawggkkVnIOzq2OujNj_7Ei_TKqX41TLPUJqo9IJLjltWFhL_0FTv3N70yt0rxuXb0r0oIlO2_TUmh6pWNJPWYhWKuFCC6fgouigwGl-RYePnJmjGcWWuTW4nsWpiBINJDv-D0Vzn7GV1PECQKY33L_4y2vzLLs77v1NXXo0qLd0gbroGUeht-B8JIW_HeOzu28wlO1HZyHLdb04p9EQ

### LIST ALL IMAGES
GET http://localhost:5000/v2/_catalog
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZMWEE6WDQ0VDpPQjNaOjY2SUc6NEoyNjpZSFNZOllTSFg6V1c2UzpENTRGOk0yRUw6SkZMTTpGQlRXIn0.eyJpc3MiOiJhdXRoX3JlZ2lzdHJ5Iiwic3ViIjoiQWxleGlzLnZpc2NvZ2xpb3NpQG91dGxvb2suZnIiLCJhdWQiOiJyZWdpc3RyeSIsImV4cCI6MzYwMTU0OTc5NzExMywibmJmIjoxNTQ5Nzk3MTAzLCJpYXQiOjE1NDk3OTcxMTMsImp0aSI6IjU1NzcwMDY3OTE5NDc3Nzk0MTAiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6IjBkODBjZjQzLWViNDUtNGNmZS1iZGQ4LTlkODJkNmM0YzI3NS9oZWxsby13b3JsZCIsImFjdGlvbnMiOlsiZGVsZXRlIiwicHVsbCIsInB1c2giXX0seyJ0eXBlIjoicmVnaXN0cnkiLCJuYW1lIjoiY2F0YWxvZyIsImFjdGlvbnMiOlsiKiJdfV19.bHxKEsorYum37c10POoEzFdpQiEZWP02swhXTYuAUxop39tUH2Qzg7SgtrlTu4KV-Nxbqic3UiBPhtgKp_tOVhrjQ_3LrBhGhRN8hjWtCL_iDSyRV8LuBF2852wZfAclvWMAIJoBLMmoQhMc38LUDR4nx-5vd_aQItJoBQx9J59QrEDP-3hkaaOifvdAcb-vM18nfy5ptXOigmlmoqo_sVNablERsVYkJN1PzfZPsk9O5wo3lq090c9XtCBN4bmXXYVCrQmgSS0KuhGRk6MVQlBHkeIaqXEyLAgG2tQ0mbxBL4AnmZtPehdIbCAnk-k0YyGhjNVuPBvD8f1ajdLOqQ

### LIST TAGS FOR A REPOSITORY
GET http://localhost:5000/v2/0d80cf43-eb45-4cfe-bdd8-9d82d6c4c275/hello-world/tags/list
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZMWEE6WDQ0VDpPQjNaOjY2SUc6NEoyNjpZSFNZOllTSFg6V1c2UzpENTRGOk0yRUw6SkZMTTpGQlRXIn0.eyJpc3MiOiJhdXRoX3JlZ2lzdHJ5Iiwic3ViIjoiQWxleGlzLnZpc2NvZ2xpb3NpQG91dGxvb2suZnIiLCJhdWQiOiJyZWdpc3RyeSIsImV4cCI6MzYwMTU0OTc5NzExMywibmJmIjoxNTQ5Nzk3MTAzLCJpYXQiOjE1NDk3OTcxMTMsImp0aSI6IjU1NzcwMDY3OTE5NDc3Nzk0MTAiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6IjBkODBjZjQzLWViNDUtNGNmZS1iZGQ4LTlkODJkNmM0YzI3NS9oZWxsby13b3JsZCIsImFjdGlvbnMiOlsiZGVsZXRlIiwicHVsbCIsInB1c2giXX0seyJ0eXBlIjoicmVnaXN0cnkiLCJuYW1lIjoiY2F0YWxvZyIsImFjdGlvbnMiOlsiKiJdfV19.bHxKEsorYum37c10POoEzFdpQiEZWP02swhXTYuAUxop39tUH2Qzg7SgtrlTu4KV-Nxbqic3UiBPhtgKp_tOVhrjQ_3LrBhGhRN8hjWtCL_iDSyRV8LuBF2852wZfAclvWMAIJoBLMmoQhMc38LUDR4nx-5vd_aQItJoBQx9J59QrEDP-3hkaaOifvdAcb-vM18nfy5ptXOigmlmoqo_sVNablERsVYkJN1PzfZPsk9O5wo3lq090c9XtCBN4bmXXYVCrQmgSS0KuhGRk6MVQlBHkeIaqXEyLAgG2tQ0mbxBL4AnmZtPehdIbCAnk-k0YyGhjNVuPBvD8f1ajdLOqQ

### LIST ALL FS LAYER OF AN IMAGE
GET http://localhost:5000/v2/77571659-d61a-4573-80c9-5af5471eed4d/redis/manifests/sha256:d0f1abb827b2763edef625926fea4a68fdc2562483d423467a2861826930409f
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZMWEE6WDQ0VDpPQjNaOjY2SUc6NEoyNjpZSFNZOllTSFg6V1c2UzpENTRGOk0yRUw6SkZMTTpGQlRXIn0.eyJpc3MiOiJhdXRoX3JlZ2lzdHJ5Iiwic3ViIjoiQWxleGlzLnZpc2NvZ2xpb3NpQG91dGxvb2suZnIiLCJhdWQiOiJyZWdpc3RyeSIsImV4cCI6MzYwMTU1NDIyNzI4NSwibmJmIjoxNTU0MjI3Mjc1LCJpYXQiOjE1NTQyMjcyODUsImp0aSI6IjU1NzcwMDY3OTE5NDc3Nzk0MTAiLCJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6Ijc3NTcxNjU5LWQ2MWEtNDU3My04MGM5LTVhZjU0NzFlZWQ0ZC9yZWRpcyIsImFjdGlvbnMiOlsiZGVsZXRlIiwicHVsbCIsInB1c2giXX1dfQ.ljZY-qZ1m8_eidACX079bW38wisTxf_Yk-xlstDXu0dgEMR9yDL_cEenwQg6iESRcmSZzx1wK14e50gN10-Ynnnsm5-fn55rJcjqjm-HVm-TsAWBZPuUMWeoWNua173w8E4IJgS9BlPnhDJ5PwWhapeYAEK93wizxlTwwAyGl4ouDH8mYRYE5RqYdRqzaPHXQXaR_vZZRkOZrblrBOC7nw4YOZqJ64Gt4AVL2jQ6Mj41EPO1MOXKLNcaDQJ8Zvij2VF1gqkThnfewpjwWlnxZi0c0t3tnS7UrHo6r7gv0vnXv-15mZeRiM2k807Fn9TXmHU_g27Qw4ClYSTHj0kXFA

###

