### Create new hello container
POST http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: 98e4ecbc645a440dbcb5d78984aa8b75

{
  "name": "hello",
  "image": "google/golang-hello",
  "plan_id": "1e006139-7010-4f5b-8d7f-be68b34badd1",
  "tags": ["123", "test"],
  "environment": {
    "PORT": "80"
  }
}

### Create new ghost container
POST http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: 98e4ecbc645a440dbcb5d78984aa8b75

{
  "name": "ghost",
  "image": "ghost",
  "plan_id": "1e006139-7010-4f5b-8d7f-be68b34badd1",
  "tags": ["123", "test"],
  "environment": {
    "server__host": "0.0.0.0",
    "server__port": "80"
  }
}

### Get list of all tags for owner id
GET http://localhost:3000/v1/containers
Authorization: ce41f7ca970745409a47079c2ebd62f2

### List containers
GET http://localhost:3000/v1/containers
Content-Type: application/json
Authorization: c2e827438b6a4a26b8262d89e2673ed0

### List images
GET http://localhost:3000/v1/images
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

### Detail image
GET http://localhost:3000/v1/images/golang:latest
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f

### Delete image
DELETE http://localhost:3000/v1/images/f3b994e2-df4c-408a-ad83-afa937a6f66b
Content-Type: application/json
Authorization: 345c9f3657b3457b8b7fe37aceb4889f
