BOX = "ubuntu/xenial64"

Vagrant.configure(2) do |config|
  config.vm.box = BOX
  config.vm.box_check_update = true

  config.vm.network "private_network", type: "dhcp"
  for i in 0..2000 do
    config.vm.network "forwarded_port", guest: 3000 + i, host: 3000 + i, protocol: "tcp"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.synced_folder "#{File.dirname(__FILE__)}/../", "/home/vagrant/expected"
  config.vm.provision "shell", path: "#{File.dirname(__FILE__)}/provision.sh"
end
