// Code generated by protoc-gen-go. DO NOT EDIT.
// source: container.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	container.proto
	image.proto

It has these top-level messages:
	ChangeContainerStateRequest
	ChangeContainerStateReply
	DeleteImageRequest
	DeleteImageReply
	GenerateTokenRequest
	GenerateTokenReply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_START State = 0
	State_STOP  State = 1
)

var State_name = map[int32]string{
	0: "START",
	1: "STOP",
}
var State_value = map[string]int32{
	"START": 0,
	"STOP":  1,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ChangeContainerStateRequest struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RequestedState State  `protobuf:"varint,2,opt,name=requestedState,enum=protocol.State" json:"requestedState,omitempty"`
}

func (m *ChangeContainerStateRequest) Reset()                    { *m = ChangeContainerStateRequest{} }
func (m *ChangeContainerStateRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateRequest) ProtoMessage()               {}
func (*ChangeContainerStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChangeContainerStateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeContainerStateRequest) GetRequestedState() State {
	if m != nil {
		return m.RequestedState
	}
	return State_START
}

type ChangeContainerStateReply struct {
}

func (m *ChangeContainerStateReply) Reset()                    { *m = ChangeContainerStateReply{} }
func (m *ChangeContainerStateReply) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateReply) ProtoMessage()               {}
func (*ChangeContainerStateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ChangeContainerStateRequest)(nil), "protocol.ChangeContainerStateRequest")
	proto.RegisterType((*ChangeContainerStateReply)(nil), "protocol.ChangeContainerStateReply")
	proto.RegisterEnum("protocol.State", State_name, State_value)
}

func init() { proto.RegisterFile("container.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0x2b,
	0x49, 0xcc, 0xcc, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9,
	0xf9, 0x39, 0x4a, 0x69, 0x5c, 0xd2, 0xce, 0x19, 0x89, 0x79, 0xe9, 0xa9, 0xce, 0x30, 0x25, 0xc1,
	0x25, 0x89, 0x25, 0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0xe6, 0x5c, 0x7c, 0x45,
	0x10, 0xa9, 0xd4, 0x14, 0xb0, 0x42, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x7e, 0x3d, 0x98,
	0x89, 0x7a, 0x10, 0xfd, 0x68, 0xca, 0x94, 0xa4, 0xb9, 0x24, 0xb1, 0xdb, 0x53, 0x90, 0x53, 0xa9,
	0x25, 0xc3, 0xc5, 0x0a, 0xe6, 0x09, 0x71, 0x72, 0xb1, 0x06, 0x87, 0x38, 0x06, 0x85, 0x08, 0x30,
	0x08, 0x71, 0x70, 0xb1, 0x04, 0x87, 0xf8, 0x07, 0x08, 0x30, 0x26, 0xb1, 0x81, 0x8d, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xbc, 0x28, 0x71, 0xc6, 0x00, 0x00, 0x00,
}
