// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	controller.proto
	image.proto

It has these top-level messages:
	ChangeContainerStateRequest
	ChangeContainerStateReply
	GetContainersLogsRequest
	GetContainersLogsReply
	DeleteImageRequest
	DeleteImageReply
	GenerateTokenRequest
	GenerateTokenReply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeContainerStateRequest_State int32

const (
	ChangeContainerStateRequest_START ChangeContainerStateRequest_State = 0
	ChangeContainerStateRequest_STOP  ChangeContainerStateRequest_State = 1
)

var ChangeContainerStateRequest_State_name = map[int32]string{
	0: "START",
	1: "STOP",
}
var ChangeContainerStateRequest_State_value = map[string]int32{
	"START": 0,
	"STOP":  1,
}

func (x ChangeContainerStateRequest_State) String() string {
	return proto.EnumName(ChangeContainerStateRequest_State_name, int32(x))
}
func (ChangeContainerStateRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type GetContainersLogsReply_Output int32

const (
	GetContainersLogsReply_STDOUT GetContainersLogsReply_Output = 0
	GetContainersLogsReply_STDERR GetContainersLogsReply_Output = 1
)

var GetContainersLogsReply_Output_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
}
var GetContainersLogsReply_Output_value = map[string]int32{
	"STDOUT": 0,
	"STDERR": 1,
}

func (x GetContainersLogsReply_Output) String() string {
	return proto.EnumName(GetContainersLogsReply_Output_name, int32(x))
}
func (GetContainersLogsReply_Output) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type ChangeContainerStateRequest struct {
	Id             string                            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RequestedState ChangeContainerStateRequest_State `protobuf:"varint,2,opt,name=requestedState,enum=protocol.ChangeContainerStateRequest_State" json:"requestedState,omitempty"`
}

func (m *ChangeContainerStateRequest) Reset()                    { *m = ChangeContainerStateRequest{} }
func (m *ChangeContainerStateRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateRequest) ProtoMessage()               {}
func (*ChangeContainerStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChangeContainerStateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeContainerStateRequest) GetRequestedState() ChangeContainerStateRequest_State {
	if m != nil {
		return m.RequestedState
	}
	return ChangeContainerStateRequest_START
}

type ChangeContainerStateReply struct {
}

func (m *ChangeContainerStateReply) Reset()                    { *m = ChangeContainerStateReply{} }
func (m *ChangeContainerStateReply) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateReply) ProtoMessage()               {}
func (*ChangeContainerStateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetContainersLogsRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetContainersLogsRequest) Reset()                    { *m = GetContainersLogsRequest{} }
func (m *GetContainersLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetContainersLogsRequest) ProtoMessage()               {}
func (*GetContainersLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetContainersLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContainersLogsReply struct {
	Output  GetContainersLogsReply_Output `protobuf:"varint,1,opt,name=output,enum=protocol.GetContainersLogsReply_Output" json:"output,omitempty"`
	Message string                        `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Time    *google_protobuf.Timestamp    `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *GetContainersLogsReply) Reset()                    { *m = GetContainersLogsReply{} }
func (m *GetContainersLogsReply) String() string            { return proto.CompactTextString(m) }
func (*GetContainersLogsReply) ProtoMessage()               {}
func (*GetContainersLogsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetContainersLogsReply) GetOutput() GetContainersLogsReply_Output {
	if m != nil {
		return m.Output
	}
	return GetContainersLogsReply_STDOUT
}

func (m *GetContainersLogsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetContainersLogsReply) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeContainerStateRequest)(nil), "protocol.ChangeContainerStateRequest")
	proto.RegisterType((*ChangeContainerStateReply)(nil), "protocol.ChangeContainerStateReply")
	proto.RegisterType((*GetContainersLogsRequest)(nil), "protocol.GetContainersLogsRequest")
	proto.RegisterType((*GetContainersLogsReply)(nil), "protocol.GetContainersLogsReply")
	proto.RegisterEnum("protocol.ChangeContainerStateRequest_State", ChangeContainerStateRequest_State_name, ChangeContainerStateRequest_State_value)
	proto.RegisterEnum("protocol.GetContainersLogsReply_Output", GetContainersLogsReply_Output_name, GetContainersLogsReply_Output_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Controller service

type ControllerClient interface {
	ChangeContainerState(ctx context.Context, in *ChangeContainerStateRequest, opts ...grpc.CallOption) (*ChangeContainerStateReply, error)
	GetContainerLogs(ctx context.Context, in *GetContainersLogsRequest, opts ...grpc.CallOption) (Controller_GetContainerLogsClient, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) ChangeContainerState(ctx context.Context, in *ChangeContainerStateRequest, opts ...grpc.CallOption) (*ChangeContainerStateReply, error) {
	out := new(ChangeContainerStateReply)
	err := grpc.Invoke(ctx, "/protocol.Controller/ChangeContainerState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetContainerLogs(ctx context.Context, in *GetContainersLogsRequest, opts ...grpc.CallOption) (Controller_GetContainerLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[0], c.cc, "/protocol.Controller/GetContainerLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerGetContainerLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_GetContainerLogsClient interface {
	Recv() (*GetContainersLogsReply, error)
	grpc.ClientStream
}

type controllerGetContainerLogsClient struct {
	grpc.ClientStream
}

func (x *controllerGetContainerLogsClient) Recv() (*GetContainersLogsReply, error) {
	m := new(GetContainersLogsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Controller service

type ControllerServer interface {
	ChangeContainerState(context.Context, *ChangeContainerStateRequest) (*ChangeContainerStateReply, error)
	GetContainerLogs(*GetContainersLogsRequest, Controller_GetContainerLogsServer) error
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_ChangeContainerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeContainerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ChangeContainerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Controller/ChangeContainerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ChangeContainerState(ctx, req.(*ChangeContainerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetContainersLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).GetContainerLogs(m, &controllerGetContainerLogsServer{stream})
}

type Controller_GetContainerLogsServer interface {
	Send(*GetContainersLogsReply) error
	grpc.ServerStream
}

type controllerGetContainerLogsServer struct {
	grpc.ServerStream
}

func (x *controllerGetContainerLogsServer) Send(m *GetContainersLogsReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeContainerState",
			Handler:    _Controller_ChangeContainerState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerLogs",
			Handler:       _Controller_GetContainerLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xd1, 0x4a, 0xf3, 0x30,
	0x18, 0x86, 0x97, 0xfd, 0x5b, 0xff, 0xed, 0x13, 0x4a, 0x09, 0x22, 0x75, 0x13, 0x2c, 0x11, 0x71,
	0x28, 0x64, 0x52, 0x2f, 0x40, 0x64, 0x8a, 0x27, 0xc2, 0x24, 0xad, 0x67, 0x9e, 0x74, 0x6b, 0xac,
	0x85, 0xb6, 0xa9, 0x6d, 0x7a, 0xb0, 0xbb, 0xf1, 0x66, 0x3c, 0xf7, 0x92, 0xa4, 0x89, 0x9d, 0x22,
	0x75, 0xf3, 0xa8, 0x49, 0xf3, 0x7c, 0x6f, 0x9b, 0xe7, 0x05, 0x6b, 0x29, 0x32, 0x59, 0x88, 0x24,
	0xe1, 0x05, 0xcd, 0x0b, 0x21, 0x05, 0x1e, 0xa8, 0xc7, 0x52, 0x24, 0xa3, 0xc3, 0x48, 0x88, 0x28,
	0xe1, 0x53, 0xf5, 0x62, 0x51, 0x3d, 0x4d, 0x65, 0x9c, 0xf2, 0x52, 0x06, 0x69, 0xae, 0x51, 0xf2,
	0x8a, 0x60, 0x3c, 0x7b, 0x0e, 0xb2, 0x88, 0xcf, 0x44, 0x26, 0x83, 0x38, 0xe3, 0x85, 0x27, 0x03,
	0xc9, 0x19, 0x7f, 0xa9, 0x78, 0x29, 0xb1, 0x09, 0xdd, 0x38, 0xb4, 0x91, 0x83, 0x26, 0x43, 0xd6,
	0x8d, 0x43, 0xec, 0x81, 0x59, 0xe8, 0x23, 0x1e, 0x2a, 0xd0, 0xee, 0x3a, 0x68, 0x62, 0xba, 0x67,
	0xb4, 0xf9, 0x26, 0xdd, 0x10, 0x47, 0xf5, 0xe6, 0x47, 0x04, 0x39, 0x80, 0xbe, 0x5a, 0xe0, 0x21,
	0xf4, 0x3d, 0xff, 0x8a, 0xf9, 0x56, 0x07, 0x0f, 0xa0, 0xe7, 0xf9, 0xf3, 0x7b, 0x0b, 0x91, 0x31,
	0xec, 0xb7, 0x47, 0xe6, 0xc9, 0x8a, 0x9c, 0x82, 0x7d, 0xcb, 0xe5, 0xfa, 0xa4, 0xbc, 0x13, 0x51,
	0xf9, 0xcb, 0xbf, 0x93, 0x37, 0x04, 0x7b, 0x2d, 0x70, 0x9e, 0xac, 0xf0, 0x25, 0x18, 0xa2, 0x92,
	0x79, 0x25, 0x15, 0x6e, 0xba, 0x27, 0x5f, 0xd7, 0x69, 0x9f, 0xa0, 0x73, 0x85, 0xb3, 0xcf, 0x31,
	0x6c, 0xc3, 0xff, 0x94, 0x97, 0x65, 0x10, 0x69, 0x21, 0x43, 0xd6, 0x6c, 0x31, 0x85, 0x5e, 0x2d,
	0xdd, 0xfe, 0xe7, 0xa0, 0xc9, 0x8e, 0x3b, 0xa2, 0xba, 0x11, 0xda, 0x34, 0x42, 0xfd, 0xa6, 0x11,
	0xa6, 0x38, 0xe2, 0x80, 0xa1, 0xb3, 0x31, 0x80, 0xe1, 0xf9, 0xd7, 0xf3, 0x87, 0x5a, 0x87, 0x5e,
	0xdf, 0x30, 0x66, 0x21, 0xf7, 0x1d, 0x01, 0xcc, 0xd6, 0x9d, 0xe3, 0x10, 0x76, 0xdb, 0xfc, 0xe0,
	0xe3, 0x3f, 0x55, 0x32, 0x3a, 0xda, 0x86, 0xd5, 0x9a, 0x3b, 0xf8, 0x11, 0xac, 0xef, 0x26, 0x6a,
	0x11, 0x98, 0x6c, 0xb4, 0xa4, 0xe3, 0x9d, 0x6d, 0x26, 0x49, 0xe7, 0x1c, 0x2d, 0x0c, 0x05, 0x5d,
	0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x29, 0x05, 0x73, 0xcc, 0x02, 0x00, 0x00,
}
