// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	controller.proto
	image.proto
	util.proto
	auth.proto

It has these top-level messages:
	ChangeContainerStateRequest
	ChangeContainerStateReply
	GetContainersLogsRequest
	GetContainersLogsReply
	GetContainerMetricsRequest
	GetContainerMetricsReply
	DeleteImageEvent
	DeleteImageLayerEvent
	Timestamp
	GenerateTokenRequest
	GenerateTokenReply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeContainerStateRequest_State int32

const (
	ChangeContainerStateRequest_START ChangeContainerStateRequest_State = 0
	ChangeContainerStateRequest_STOP  ChangeContainerStateRequest_State = 1
)

var ChangeContainerStateRequest_State_name = map[int32]string{
	0: "START",
	1: "STOP",
}
var ChangeContainerStateRequest_State_value = map[string]int32{
	"START": 0,
	"STOP":  1,
}

func (x ChangeContainerStateRequest_State) String() string {
	return proto.EnumName(ChangeContainerStateRequest_State_name, int32(x))
}
func (ChangeContainerStateRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type GetContainersLogsReply_Output int32

const (
	GetContainersLogsReply_STDOUT GetContainersLogsReply_Output = 0
	GetContainersLogsReply_STDERR GetContainersLogsReply_Output = 1
)

var GetContainersLogsReply_Output_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
}
var GetContainersLogsReply_Output_value = map[string]int32{
	"STDOUT": 0,
	"STDERR": 1,
}

func (x GetContainersLogsReply_Output) String() string {
	return proto.EnumName(GetContainersLogsReply_Output_name, int32(x))
}
func (GetContainersLogsReply_Output) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type ChangeContainerStateRequest struct {
	Id             string                            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RequestedState ChangeContainerStateRequest_State `protobuf:"varint,2,opt,name=requestedState,enum=protocol.ChangeContainerStateRequest_State" json:"requestedState,omitempty"`
}

func (m *ChangeContainerStateRequest) Reset()                    { *m = ChangeContainerStateRequest{} }
func (m *ChangeContainerStateRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateRequest) ProtoMessage()               {}
func (*ChangeContainerStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChangeContainerStateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChangeContainerStateRequest) GetRequestedState() ChangeContainerStateRequest_State {
	if m != nil {
		return m.RequestedState
	}
	return ChangeContainerStateRequest_START
}

type ChangeContainerStateReply struct {
}

func (m *ChangeContainerStateReply) Reset()                    { *m = ChangeContainerStateReply{} }
func (m *ChangeContainerStateReply) String() string            { return proto.CompactTextString(m) }
func (*ChangeContainerStateReply) ProtoMessage()               {}
func (*ChangeContainerStateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetContainersLogsRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetContainersLogsRequest) Reset()                    { *m = GetContainersLogsRequest{} }
func (m *GetContainersLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetContainersLogsRequest) ProtoMessage()               {}
func (*GetContainersLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetContainersLogsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContainersLogsReply struct {
	Output  GetContainersLogsReply_Output `protobuf:"varint,1,opt,name=output,enum=protocol.GetContainersLogsReply_Output" json:"output,omitempty"`
	Time    *Timestamp                    `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	TaskId  string                        `protobuf:"bytes,3,opt,name=taskId" json:"taskId,omitempty"`
	Message string                        `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
}

func (m *GetContainersLogsReply) Reset()                    { *m = GetContainersLogsReply{} }
func (m *GetContainersLogsReply) String() string            { return proto.CompactTextString(m) }
func (*GetContainersLogsReply) ProtoMessage()               {}
func (*GetContainersLogsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetContainersLogsReply) GetOutput() GetContainersLogsReply_Output {
	if m != nil {
		return m.Output
	}
	return GetContainersLogsReply_STDOUT
}

func (m *GetContainersLogsReply) GetTime() *Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GetContainersLogsReply) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *GetContainersLogsReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetContainerMetricsRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetContainerMetricsRequest) Reset()                    { *m = GetContainerMetricsRequest{} }
func (m *GetContainerMetricsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetContainerMetricsRequest) ProtoMessage()               {}
func (*GetContainerMetricsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetContainerMetricsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContainerMetricsReply struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *GetContainerMetricsReply) Reset()                    { *m = GetContainerMetricsReply{} }
func (m *GetContainerMetricsReply) String() string            { return proto.CompactTextString(m) }
func (*GetContainerMetricsReply) ProtoMessage()               {}
func (*GetContainerMetricsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetContainerMetricsReply) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeContainerStateRequest)(nil), "protocol.ChangeContainerStateRequest")
	proto.RegisterType((*ChangeContainerStateReply)(nil), "protocol.ChangeContainerStateReply")
	proto.RegisterType((*GetContainersLogsRequest)(nil), "protocol.GetContainersLogsRequest")
	proto.RegisterType((*GetContainersLogsReply)(nil), "protocol.GetContainersLogsReply")
	proto.RegisterType((*GetContainerMetricsRequest)(nil), "protocol.GetContainerMetricsRequest")
	proto.RegisterType((*GetContainerMetricsReply)(nil), "protocol.GetContainerMetricsReply")
	proto.RegisterEnum("protocol.ChangeContainerStateRequest_State", ChangeContainerStateRequest_State_name, ChangeContainerStateRequest_State_value)
	proto.RegisterEnum("protocol.GetContainersLogsReply_Output", GetContainersLogsReply_Output_name, GetContainersLogsReply_Output_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Controller service

type ControllerClient interface {
	ChangeContainerState(ctx context.Context, in *ChangeContainerStateRequest, opts ...grpc.CallOption) (*ChangeContainerStateReply, error)
	GetContainerLogs(ctx context.Context, in *GetContainersLogsRequest, opts ...grpc.CallOption) (Controller_GetContainerLogsClient, error)
	GetContainerMetrics(ctx context.Context, in *GetContainerMetricsRequest, opts ...grpc.CallOption) (Controller_GetContainerMetricsClient, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) ChangeContainerState(ctx context.Context, in *ChangeContainerStateRequest, opts ...grpc.CallOption) (*ChangeContainerStateReply, error) {
	out := new(ChangeContainerStateReply)
	err := grpc.Invoke(ctx, "/protocol.Controller/ChangeContainerState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) GetContainerLogs(ctx context.Context, in *GetContainersLogsRequest, opts ...grpc.CallOption) (Controller_GetContainerLogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[0], c.cc, "/protocol.Controller/GetContainerLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerGetContainerLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_GetContainerLogsClient interface {
	Recv() (*GetContainersLogsReply, error)
	grpc.ClientStream
}

type controllerGetContainerLogsClient struct {
	grpc.ClientStream
}

func (x *controllerGetContainerLogsClient) Recv() (*GetContainersLogsReply, error) {
	m := new(GetContainersLogsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) GetContainerMetrics(ctx context.Context, in *GetContainerMetricsRequest, opts ...grpc.CallOption) (Controller_GetContainerMetricsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Controller_serviceDesc.Streams[1], c.cc, "/protocol.Controller/GetContainerMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerGetContainerMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_GetContainerMetricsClient interface {
	Recv() (*GetContainerMetricsReply, error)
	grpc.ClientStream
}

type controllerGetContainerMetricsClient struct {
	grpc.ClientStream
}

func (x *controllerGetContainerMetricsClient) Recv() (*GetContainerMetricsReply, error) {
	m := new(GetContainerMetricsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Controller service

type ControllerServer interface {
	ChangeContainerState(context.Context, *ChangeContainerStateRequest) (*ChangeContainerStateReply, error)
	GetContainerLogs(*GetContainersLogsRequest, Controller_GetContainerLogsServer) error
	GetContainerMetrics(*GetContainerMetricsRequest, Controller_GetContainerMetricsServer) error
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_ChangeContainerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeContainerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ChangeContainerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Controller/ChangeContainerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ChangeContainerState(ctx, req.(*ChangeContainerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_GetContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetContainersLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).GetContainerLogs(m, &controllerGetContainerLogsServer{stream})
}

type Controller_GetContainerLogsServer interface {
	Send(*GetContainersLogsReply) error
	grpc.ServerStream
}

type controllerGetContainerLogsServer struct {
	grpc.ServerStream
}

func (x *controllerGetContainerLogsServer) Send(m *GetContainersLogsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_GetContainerMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetContainerMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).GetContainerMetrics(m, &controllerGetContainerMetricsServer{stream})
}

type Controller_GetContainerMetricsServer interface {
	Send(*GetContainerMetricsReply) error
	grpc.ServerStream
}

type controllerGetContainerMetricsServer struct {
	grpc.ServerStream
}

func (x *controllerGetContainerMetricsServer) Send(m *GetContainerMetricsReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeContainerState",
			Handler:    _Controller_ChangeContainerState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContainerLogs",
			Handler:       _Controller_GetContainerLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetContainerMetrics",
			Handler:       _Controller_GetContainerMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controller.proto",
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0xed, 0x60, 0x8b, 0xed, 0xd5, 0x10, 0x72, 0x6b, 0x1a, 0xa4, 0x3e, 0x90, 0x51, 0xd3, 0x46,
	0x0d, 0x31, 0xe8, 0xbb, 0x31, 0xd5, 0x18, 0x13, 0x4d, 0x0d, 0xe0, 0xdb, 0xbe, 0xb0, 0x30, 0xe9,
	0x92, 0x05, 0x86, 0x85, 0xe1, 0xa1, 0x7f, 0xb3, 0x3f, 0xb1, 0xbf, 0xb2, 0xdf, 0xb3, 0x61, 0x68,
	0x69, 0xbb, 0xa1, 0xed, 0x3e, 0x31, 0x97, 0x7b, 0xce, 0x99, 0x33, 0xe7, 0x5e, 0xd0, 0x43, 0x9e,
	0x89, 0x82, 0x27, 0x09, 0x2b, 0xec, 0xbc, 0xe0, 0x82, 0xe3, 0x50, 0x7e, 0x42, 0x9e, 0x98, 0x50,
	0x89, 0x38, 0x69, 0xfe, 0xd2, 0x5b, 0x02, 0xd3, 0xc5, 0x55, 0x90, 0xad, 0xd8, 0x82, 0x67, 0x22,
	0x88, 0x33, 0x56, 0x78, 0x22, 0x10, 0xcc, 0x65, 0x37, 0x15, 0x2b, 0x05, 0x6a, 0xa0, 0xc4, 0x91,
	0x41, 0x2c, 0x32, 0x1f, 0xb9, 0x4a, 0x1c, 0xa1, 0x07, 0x5a, 0xd1, 0xb4, 0x58, 0x24, 0x81, 0x86,
	0x62, 0x91, 0xb9, 0xe6, 0x7c, 0xb4, 0xb7, 0xf2, 0xf6, 0x09, 0x39, 0xbb, 0x29, 0x1e, 0x49, 0xd0,
	0x37, 0x30, 0x90, 0x07, 0x1c, 0xc1, 0xc0, 0xf3, 0xbf, 0xbb, 0xbe, 0xde, 0xc3, 0x21, 0xf4, 0x3d,
	0x7f, 0xf9, 0x4f, 0x27, 0x74, 0x0a, 0xaf, 0xbb, 0x25, 0xf3, 0x64, 0x4d, 0x3f, 0x80, 0xf1, 0x8b,
	0x89, 0xb6, 0x53, 0xfe, 0xe1, 0xab, 0xf2, 0x88, 0x77, 0x7a, 0x4f, 0x60, 0xd2, 0x01, 0xce, 0x93,
	0x35, 0x7e, 0x03, 0x95, 0x57, 0x22, 0xaf, 0x84, 0x84, 0x6b, 0xce, 0x6c, 0xf7, 0x9c, 0x6e, 0x86,
	0xbd, 0x94, 0x70, 0x77, 0x43, 0xc3, 0x19, 0xf4, 0x45, 0x9c, 0x36, 0x69, 0xbc, 0x70, 0xc6, 0x3b,
	0xba, 0x1f, 0xa7, 0xac, 0x14, 0x41, 0x9a, 0xbb, 0x12, 0x80, 0x13, 0x50, 0x45, 0x50, 0x5e, 0xff,
	0x8e, 0x8c, 0x67, 0xd2, 0xd8, 0xa6, 0x42, 0x03, 0x9e, 0xa7, 0xac, 0x2c, 0x83, 0x15, 0x33, 0xfa,
	0xb2, 0xb1, 0x2d, 0xa9, 0x05, 0x6a, 0x73, 0x19, 0x02, 0xa8, 0x9e, 0xff, 0x63, 0xf9, 0xbf, 0xce,
	0xa7, 0x39, 0xff, 0x74, 0x5d, 0x9d, 0xd0, 0x4f, 0x60, 0xee, 0xbb, 0xfc, 0xcb, 0x44, 0x11, 0x87,
	0x47, 0x63, 0xf8, 0x7a, 0x18, 0x59, 0x8b, 0xae, 0x73, 0xd8, 0x73, 0x51, 0x13, 0x5e, 0xb6, 0x2e,
	0x9c, 0x3b, 0x05, 0x60, 0xd1, 0xee, 0x14, 0x46, 0xf0, 0xaa, 0x6b, 0x28, 0xf8, 0xfe, 0x49, 0x7b,
	0x60, 0xbe, 0x3d, 0x07, 0xab, 0x67, 0xdb, 0xc3, 0x0b, 0xd0, 0xf7, 0xad, 0xd6, 0xe9, 0x23, 0x3d,
	0x39, 0x9a, 0x46, 0xde, 0x3a, 0x37, 0x3e, 0xda, 0xfb, 0x4c, 0x30, 0x84, 0x71, 0x47, 0x10, 0xf8,
	0xae, 0x9b, 0x7c, 0x98, 0xaa, 0x49, 0xcf, 0xa0, 0x36, 0x97, 0x5c, 0xaa, 0x12, 0xf6, 0xe5, 0x21,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0xf0, 0x03, 0x86, 0x91, 0x03, 0x00, 0x00,
}
