// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image.proto

package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DeleteImageRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteImageRequest) Reset()                    { *m = DeleteImageRequest{} }
func (m *DeleteImageRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteImageRequest) ProtoMessage()               {}
func (*DeleteImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DeleteImageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteImageReply struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteImageReply) Reset()                    { *m = DeleteImageReply{} }
func (m *DeleteImageReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteImageReply) ProtoMessage()               {}
func (*DeleteImageReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DeleteImageReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type GenerateTokenRequest struct {
	ImageName     string `protobuf:"bytes,1,opt,name=imageName" json:"imageName,omitempty"`
	TokenDuration int64  `protobuf:"varint,2,opt,name=tokenDuration" json:"tokenDuration,omitempty"`
}

func (m *GenerateTokenRequest) Reset()                    { *m = GenerateTokenRequest{} }
func (m *GenerateTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateTokenRequest) ProtoMessage()               {}
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GenerateTokenRequest) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *GenerateTokenRequest) GetTokenDuration() int64 {
	if m != nil {
		return m.TokenDuration
	}
	return 0
}

type GenerateTokenReply struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GenerateTokenReply) Reset()                    { *m = GenerateTokenReply{} }
func (m *GenerateTokenReply) String() string            { return proto.CompactTextString(m) }
func (*GenerateTokenReply) ProtoMessage()               {}
func (*GenerateTokenReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GenerateTokenReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GenerateTokenReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteImageRequest)(nil), "protocol.DeleteImageRequest")
	proto.RegisterType((*DeleteImageReply)(nil), "protocol.DeleteImageReply")
	proto.RegisterType((*GenerateTokenRequest)(nil), "protocol.GenerateTokenRequest")
	proto.RegisterType((*GenerateTokenReply)(nil), "protocol.GenerateTokenReply")
}

func init() { proto.RegisterFile("image.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x4d, 0x4c,
	0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x2a,
	0x5c, 0x42, 0x2e, 0xa9, 0x39, 0xa9, 0x25, 0xa9, 0x9e, 0x20, 0xe9, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6,
	0xcc, 0x14, 0x25, 0x0d, 0x2e, 0x01, 0x14, 0x55, 0x05, 0x39, 0x95, 0x42, 0x22, 0x5c, 0xac, 0xa9,
	0x45, 0x45, 0xf9, 0x45, 0x50, 0x65, 0x10, 0x8e, 0x52, 0x14, 0x97, 0x88, 0x7b, 0x6a, 0x5e, 0x6a,
	0x51, 0x62, 0x49, 0x6a, 0x48, 0x7e, 0x76, 0x6a, 0x1e, 0xcc, 0x44, 0x19, 0x2e, 0x4e, 0xb0, 0x03,
	0xfc, 0x12, 0x73, 0x53, 0xa1, 0x3a, 0x10, 0x02, 0x42, 0x2a, 0x5c, 0xbc, 0x25, 0x20, 0xd5, 0x2e,
	0xa5, 0x45, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0xa8, 0x82,
	0x4a, 0x0e, 0x5c, 0x42, 0x68, 0x66, 0x43, 0xdd, 0x01, 0x56, 0x06, 0x73, 0x07, 0x98, 0x83, 0x70,
	0x1d, 0x13, 0x92, 0xeb, 0x92, 0xd8, 0xc0, 0xfe, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0xa4, 0x76, 0x38, 0x0d, 0x01, 0x00, 0x00,
}
