// Code generated by protoc-gen-go. DO NOT EDIT.
// source: util.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	util.proto
	auth.proto
	controller.proto
	image.proto

It has these top-level messages:
	Timestamp
	GenerateTokenRequest
	GenerateTokenReply
	ChangeContainerStateRequest
	ChangeContainerStateReply
	GetContainersLogsRequest
	GetContainersLogsReply
	DeleteImageEvent
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Second     int64 `protobuf:"varint,1,opt,name=second" json:"second,omitempty"`
	NanoSecond int64 `protobuf:"varint,2,opt,name=nanoSecond" json:"nanoSecond,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timestamp) GetSecond() int64 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *Timestamp) GetNanoSecond() int64 {
	if m != nil {
		return m.NanoSecond
	}
	return 0
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "protocol.Timestamp")
}

func init() { proto.RegisterFile("util.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0xc9, 0xcc,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xce, 0x5c,
	0x9c, 0x21, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xa9,
	0xc9, 0xf9, 0x79, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x50, 0x9e, 0x90, 0x1c, 0x17,
	0x57, 0x5e, 0x62, 0x5e, 0x7e, 0x30, 0x44, 0x8e, 0x09, 0x2c, 0x87, 0x24, 0x92, 0xc4, 0x06, 0x36,
	0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x69, 0xb3, 0x7c, 0x63, 0x00, 0x00, 0x00,
}
